---
title: "Palmer Penguins Dashboard"
author: Amara Brown
format: dashboard
---

```{r, echo = FALSE}
library(tidyverse)
library(plotly)
library(janitor)

penguins <- read_csv("data/penguins_lter.csv")

penguins <- penguins %>%
  clean_names()
```

Instructions: Make a dashboard with two rows. Row 1 should contain two graphs showing any penguins data you'd like. Row 2 should contain a table (use kintr::kable and select if you'd like to narrow down the columns). Then customize your dashboard by adding colors, labels, interactivity, etc.

Optional: add text cards, value box, tabs, pages, etc.

## Row 1

```{r}
#| title: scatter plot
p1 <- ggplot(data = penguins, aes(x = body_mass_g, y = flipper_length_mm)) +
  geom_point()

ggplotly(p1)
```

```{r}
#| title: bar chart

p2 <- ggplot(data = penguins, aes(x = body_mass_g, y = flipper_length_mm)) +
  geom_bar(stat="identity") +
  theme(axis,title.x = element_text(angle = 45, vjust = .5, hjust = 1))

ggplotly(p2)
```

## Row 2

```{r}
#| title: table

penguins <- penguins %>%
  select(-comments)

knitr::kable(penguins)
```
